import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Database, Download, Eye, FileUp, Pencil, Play, Plus, RefreshCw, RotateCcw, Search, Sparkles, Square, Trash2, XCircle } from "lucide-react";
import { type FormEvent, useDeferredValue, useMemo, useState } from "react";

import { api } from "../api/client";
import type { AiFindingType, AiInferenceActionPayload, AiInferenceFindingPayload, AiInferenceRun, AiInferenceRunPayload, AiInferenceStatus, AiModelAsset, AttachmentRecord, ForestBlockOption } from "../api/types";
import { AttachmentSelector } from "../components/AttachmentSelector";
import { ForestBlockSelector } from "../components/ForestBlockSelector";
import { LedgerPagination } from "../components/LedgerPagination";
import { QueryState } from "../components/QueryState";
import { SidePanel } from "../components/SidePanel";
import { hasPermission, useCapabilities } from "../hooks/useCapabilities";

const PAGE_SIZE = 30;
const STATUS_LABELS: Record<AiInferenceStatus, string> = { queued: "排队中", running: "运行中", succeeded: "已成功", failed: "已失败", cancelled: "已取消" };
const FINDING_TYPES: Record<AiFindingType, string> = { pest: "虫害", fire: "火情", disease: "病害", "illegal-cutting": "盗伐", "road-damage": "道路损坏", "tree-fall": "倒伏", other: "其他" };
type ActionKind = "succeed" | "fail" | "create-finding";

export function AiInferencePage() {
  const client = useQueryClient();
  const capabilities = useCapabilities();
  const [q, setQ] = useState("");
  const [status, setStatus] = useState("");
  const [modelAssetId, setModelAssetId] = useState("");
  const [includeDeleted, setIncludeDeleted] = useState(false);
  const [offset, setOffset] = useState(0);
  const [creating, setCreating] = useState(false);
  const [selected, setSelected] = useState<AiInferenceRun | null>(null);
  const [editing, setEditing] = useState<AiInferenceRun | null>(null);
  const [action, setAction] = useState<{ record: AiInferenceRun; kind: ActionKind } | null>(null);
  const deferredQ = useDeferredValue(q);
  const ledger = useQuery({ queryKey: ["v2-ai-inference-runs", deferredQ, status, modelAssetId, includeDeleted, offset], queryFn: () => api.aiInferenceRuns({ q: deferredQ, status, modelAssetId, includeDeleted, limit: PAGE_SIZE, offset }), placeholderData: (previous) => previous });
  const models = useQuery({ queryKey: ["v2-ai-inference-model-options"], queryFn: () => api.aiModelAssets({ assetType: "model-version", limit: 200 }) });
  const permissions = capabilities.data?.permissions;
  const roles = capabilities.data?.principal.roles;
  const canManage = hasPermission(permissions, roles, "ai.inference.manage");
  const canOperate = hasPermission(permissions, roles, "ai.inference.operate");
  const createRun = useMutation({ mutationFn: api.createAiInferenceRun, onSuccess: async (record) => { setCreating(false); setSelected(record); await invalidate(client); } });
  const updateRun = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: AiInferenceRunPayload }) => api.updateAiInferenceRun(id, payload), onSuccess: async (record) => { setEditing(null); setSelected(record); await invalidate(client); } });
  const deleteRun = useMutation({ mutationFn: api.deleteAiInferenceRun, onSuccess: async () => { setSelected(null); await invalidate(client); } });
  const restoreRun = useMutation({ mutationFn: api.restoreAiInferenceRun, onSuccess: async (record) => { setSelected(record); await invalidate(client); } });
  const operate = useMutation({ mutationFn: ({ id, action, payload = {} }: { id: string; action: string; payload?: AiInferenceActionPayload }) => api.applyAiInferenceAction(id, action, payload), onSuccess: async (record) => { setAction(null); setSelected(record); await invalidate(client); } });
  const convert = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: AiInferenceFindingPayload }) => api.createFindingFromInference(id, payload), onSuccess: async ({ run }) => { setAction(null); setSelected(run); await invalidate(client); } });
  const items = ledger.data?.items ?? [];
  const summary = useMemo(() => ({ total: ledger.data?.total ?? 0, queued: items.filter((item) => item.status === "queued").length, running: items.filter((item) => item.status === "running").length, pendingReview: items.filter((item) => item.status === "succeeded" && !item.findingId).length }), [items, ledger.data?.total]);

  return <div className="standard-page ledger-page ai-inference-page">
    <section className="page-heading ledger-heading"><div><span className="eyebrow">AI 智能应用 / 推理运行台账</span><h1>AI 推理任务</h1><p>每次运行独立留痕，输入来自附件中心、范围来自正式林班，成功结果再转入人工复核。</p></div><div className="heading-actions"><a className="button secondary" href={`/api/v2/ai/inference-runs/export.csv?${new URLSearchParams({ q: deferredQ, status, modelAssetId }).toString()}`}><Download aria-hidden="true" />导出台账</a><button className="button secondary" type="button" onClick={() => ledger.refetch()}><RefreshCw aria-hidden="true" />刷新</button><button className="button primary" type="button" disabled={!canManage} onClick={() => setCreating(true)}><Plus aria-hidden="true" />新建任务</button></div></section>
    <section className="domain-summary-strip"><Summary label="任务总数" value={summary.total} detail="当前筛选范围" /><Summary label="排队中" value={summary.queued} detail="等待执行" /><Summary label="运行中" value={summary.running} detail="正在推理" tone="active" /><Summary label="待转成果" value={summary.pendingReview} detail="成功且未生成成果" /></section>
    <section className="ledger-shell"><div className="ledger-toolbar domain-ledger-toolbar"><label className="search-field"><Search aria-hidden="true" /><input value={q} onChange={(event) => { setQ(event.target.value); setOffset(0); }} placeholder="搜索任务编号、标题或错误信息" /></label><label className="compact-filter"><span>任务状态</span><select value={status} onChange={(event) => { setStatus(event.target.value); setOffset(0); }}><option value="">全部状态</option>{Object.entries(STATUS_LABELS).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="compact-filter"><span>模型版本</span><select value={modelAssetId} onChange={(event) => { setModelAssetId(event.target.value); setOffset(0); }}><option value="">全部模型</option>{(models.data?.items ?? []).map((model) => <option value={model.id} key={model.id}>{model.name} · {model.version}</option>)}</select></label>{canManage && <label className="toggle-filter"><input type="checkbox" checked={includeDeleted} onChange={(event) => setIncludeDeleted(event.target.checked)} /><span>显示已删除</span></label>}</div>
      <QueryState loading={ledger.isLoading} error={ledger.error}><div className="table-scroll"><table className="ledger-table"><thead><tr><th>推理任务</th><th>模型与部署</th><th>林班范围</th><th>状态</th><th>运行时间</th><th className="action-column">操作</th></tr></thead><tbody>{items.map((record) => <tr className={record.deletedAt ? "is-deleted" : ""} key={record.id} onClick={() => setSelected(record)}><td><strong>{record.title}</strong><small>{record.runNo} · {record.createdBy}</small></td><td><strong>{record.model?.name || "模型已失效"}</strong><small>{record.model?.version || "版本待补"}{record.deployment ? ` · ${record.deployment.name}` : " · 默认运行环境"}</small></td><td><strong>{record.blocks.map((item) => item.code).join("、")}</strong><small>{record.inputAttachments[0]?.originalName || "输入附件缺失"}</small></td><td><span className={`status-badge ${record.status === "succeeded" ? "success" : record.status === "failed" ? "danger" : record.status === "running" ? "active" : ""}`}>{record.deletedAt ? "已删除" : STATUS_LABELS[record.status]}</span><small>{record.findingId ? "已进入识别复核" : record.status === "succeeded" ? "待转识别成果" : ""}</small></td><td><strong>{formatDate(record.requestedAt)}</strong><small>{record.durationMs == null ? "尚未完成" : `${record.durationMs} ms`}</small></td><td className="action-column"><RowActions record={record} canManage={canManage} canOperate={canOperate} onView={setSelected} onEdit={setEditing} onAction={(kind) => setAction({ record, kind })} onOperate={(actionName) => operate.mutate({ id: record.id, action: actionName })} onDelete={() => deleteRun.mutate(record.id)} onRestore={() => restoreRun.mutate(record.id)} /></td></tr>)}{!ledger.isLoading && !items.length && <tr className="empty-row"><td colSpan={6}><div className="table-empty"><Sparkles aria-hidden="true" /><strong>当前没有 AI 推理任务</strong><p>先在模型管理建立就绪模型版本，再创建带输入附件和林班范围的任务。</p></div></td></tr>}</tbody></table></div></QueryState><LedgerPagination total={ledger.data?.total ?? 0} limit={PAGE_SIZE} offset={offset} onPage={setOffset} /></section>
    <SidePanel wide open={creating} eyebrow="推理任务" title="新建推理任务" onClose={() => !createRun.isPending && setCreating(false)}><RunForm pending={createRun.isPending} error={createRun.error} onCancel={() => setCreating(false)} onSubmit={(payload) => createRun.mutate(payload)} /></SidePanel>
    <SidePanel wide open={Boolean(editing)} eyebrow="推理任务" title={`编辑 ${editing?.runNo || "任务"}`} onClose={() => !updateRun.isPending && setEditing(null)}>{editing && <RunForm initial={editing} pending={updateRun.isPending} error={updateRun.error} onCancel={() => setEditing(null)} onSubmit={(payload) => updateRun.mutate({ id: editing.id, payload })} />}</SidePanel>
    <SidePanel wide open={Boolean(selected)} eyebrow="推理任务详情" title={selected?.title || "推理任务"} onClose={() => setSelected(null)}>{selected && <RunDetail record={selected} />}</SidePanel>
    <SidePanel wide open={Boolean(action)} eyebrow="受控状态操作" title={action ? actionTitle(action.kind) : "任务操作"} onClose={() => { if (!operate.isPending && !convert.isPending) setAction(null); }}>{action && <ActionForm action={action.kind} record={action.record} pending={operate.isPending || convert.isPending} error={operate.error || convert.error} onCancel={() => setAction(null)} onSubmit={(payload) => action.kind === "create-finding" ? convert.mutate({ id: action.record.id, payload: payload as AiInferenceFindingPayload }) : operate.mutate({ id: action.record.id, action: action.kind, payload: payload as AiInferenceActionPayload })} />}</SidePanel>
  </div>;
}

function RowActions({ record, canManage, canOperate, onView, onEdit, onAction, onOperate, onDelete, onRestore }: { record: AiInferenceRun; canManage: boolean; canOperate: boolean; onView: (record: AiInferenceRun) => void; onEdit: (record: AiInferenceRun) => void; onAction: (kind: ActionKind) => void; onOperate: (action: string) => void; onDelete: () => void; onRestore: () => void }) {
  return <div className="row-actions"><button className="icon-button" type="button" title="查看" aria-label="查看推理任务" onClick={(event) => { event.stopPropagation(); onView(record); }}><Eye aria-hidden="true" /></button>{record.deletedAt ? <button className="icon-button" type="button" title="恢复" disabled={!canManage} onClick={(event) => { event.stopPropagation(); onRestore(); }}><RotateCcw aria-hidden="true" /></button> : <>{record.status === "queued" && <><button className="icon-button" type="button" title="编辑" disabled={!canManage} onClick={(event) => { event.stopPropagation(); onEdit(record); }}><Pencil aria-hidden="true" /></button><button className="icon-button" type="button" title="开始运行" disabled={!canOperate} onClick={(event) => { event.stopPropagation(); onOperate("start"); }}><Play aria-hidden="true" /></button></>}{record.status === "running" && <><button className="icon-button" type="button" title="标记成功" disabled={!canOperate} onClick={(event) => { event.stopPropagation(); onAction("succeed"); }}><Sparkles aria-hidden="true" /></button><button className="icon-button danger-copy" type="button" title="标记失败" disabled={!canOperate} onClick={(event) => { event.stopPropagation(); onAction("fail"); }}><XCircle aria-hidden="true" /></button></>}{["queued", "running"].includes(record.status) && <button className="icon-button" type="button" title="取消任务" disabled={!canOperate} onClick={(event) => { event.stopPropagation(); if (window.confirm("确认取消该推理任务吗？")) onOperate("cancel"); }}><Square aria-hidden="true" /></button>}{record.status === "succeeded" && !record.findingId && <button className="icon-button" type="button" title="转识别成果" disabled={!canOperate} onClick={(event) => { event.stopPropagation(); onAction("create-finding"); }}><Database aria-hidden="true" /></button>}{["queued", "failed", "cancelled"].includes(record.status) && <button className="icon-button danger-copy" type="button" title="删除" disabled={!canManage} onClick={(event) => { event.stopPropagation(); if (window.confirm("确认将该任务移入回收站吗？")) onDelete(); }}><Trash2 aria-hidden="true" /></button>}</>}</div>;
}

function RunForm({ initial, pending, error, onCancel, onSubmit }: { initial?: AiInferenceRun; pending: boolean; error: Error | null; onCancel: () => void; onSubmit: (payload: AiInferenceRunPayload) => void }) {
  const [modelId, setModelId] = useState(initial?.modelAssetId || "");
  const [input, setInput] = useState<AttachmentRecord[]>(initial?.inputAttachments ?? []);
  const [attachmentsOpen, setAttachmentsOpen] = useState(false);
  const [blocks, setBlocks] = useState<ForestBlockOption[]>(initial?.blocks.map((item) => ({ id: item.id, code: item.code, name: item.code, location: "", areaMu: null, hasGeometry: true, riskLevel: null })) ?? []);
  const [blocksOpen, setBlocksOpen] = useState(false);
  const [fieldError, setFieldError] = useState("");
  const models = useQuery({ queryKey: ["v2-ai-inference-form-models"], queryFn: () => api.aiModelAssets({ assetType: "model-version", limit: 200 }) });
  const deployments = useQuery({ queryKey: ["v2-ai-inference-form-deployments", modelId], queryFn: () => api.aiModelAssets({ assetType: "deployment", limit: 200 }), select: (data) => data.items.filter((item) => item.parentId === modelId && item.status === "active") });
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setFieldError("");
    const data = new FormData(event.currentTarget);
    try {
      onSubmit({ title: field(data, "title"), modelAssetId: modelId, deploymentAssetId: field(data, "deploymentAssetId"), inputAttachmentId: input[0]?.id || "", linkedBlockCodes: blocks.map((item) => item.code), parameters: jsonField(data, "parameters") });
    } catch (submitError) {
      setFieldError(submitError instanceof Error ? submitError.message : "请检查表单内容。")
    }
  };
  return <><form className="entity-form" onSubmit={submit}><fieldset className="form-section"><legend>运行定义</legend><div className="form-grid"><label className="field-span"><span>任务标题<em>*</em></span><input name="title" required defaultValue={initial?.title} /></label><label><span>模型版本<em>*</em></span><select value={modelId} required onChange={(event) => setModelId(event.target.value)}><option value="">请选择</option>{(models.data?.items ?? []).filter((item) => ["ready", "active"].includes(item.status)).map((item) => <option value={item.id} key={item.id}>{item.name} · {item.version}</option>)}</select></label><label><span>部署实例</span><select name="deploymentAssetId" defaultValue={initial?.deploymentAssetId}><option value="">默认运行环境</option>{(deployments.data ?? []).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field-span"><span>推理参数(JSON)</span><textarea name="parameters" rows={4} defaultValue={JSON.stringify(initial?.parameters ?? {}, null, 2)} /></label></div></fieldset><fieldset className="form-section"><legend>输入与范围</legend><div className="relation-toolbar"><div><strong>输入附件<em>*</em></strong><small>必须来自正式附件中心，仅允许一个输入文件</small></div><button className="button secondary" type="button" onClick={() => setAttachmentsOpen(true)}><FileUp aria-hidden="true" />选择输入</button></div><div className="relation-chips">{input.map((item) => <span key={item.id}><strong>{item.originalName}</strong><small>{item.sha256.slice(0, 12)}</small><button type="button" onClick={() => setInput([])}>×</button></span>)}</div><div className="relation-toolbar"><div><strong>关联林班<em>*</em></strong><small>从正式林班空间台账选择，可关联多个</small></div><button className="button secondary" type="button" onClick={() => setBlocksOpen(true)}>选择林班</button></div><div className="relation-chips">{blocks.map((block) => <span key={block.id}><strong>{block.name}</strong><small>{block.code}</small><button type="button" onClick={() => setBlocks((items) => items.filter((item) => item.id !== block.id))}>×</button></span>)}</div></fieldset>{fieldError && <p className="form-error">{fieldError}</p>}{error && <p className="form-error">{error.message}</p>}<div className="form-actions"><button className="button secondary" type="button" onClick={onCancel}>取消</button><button className="button primary" disabled={pending || !modelId || !input.length || !blocks.length}>{pending ? "正在保存" : "保存任务"}</button></div></form><AttachmentSelector open={attachmentsOpen} selectedIds={input.map((item) => item.id)} title="选择推理输入文件" onClose={() => setAttachmentsOpen(false)} onChange={(items) => setInput(items.slice(-1))} /><ForestBlockSelector open={blocksOpen} onClose={() => setBlocksOpen(false)} onSelect={(block) => setBlocks((items) => items.some((item) => item.id === block.id) ? items : [...items, block])} /></>;
}

function ActionForm({ action, record, pending, error, onCancel, onSubmit }: { action: ActionKind; record: AiInferenceRun; pending: boolean; error: Error | null; onCancel: () => void; onSubmit: (payload: AiInferenceActionPayload | AiInferenceFindingPayload) => void }) {
  const [outputs, setOutputs] = useState<AttachmentRecord[]>(record.outputAttachments ?? []);
  const [open, setOpen] = useState(false);
  const [fieldError, setFieldError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setFieldError("");
    const data = new FormData(event.currentTarget);
    try {
      if (action === "succeed") onSubmit({ output: jsonField(data, "output"), outputAttachmentIds: outputs.map((item) => item.id) });
      else if (action === "fail") onSubmit({ errorMessage: field(data, "errorMessage") });
      else onSubmit({ title: field(data, "title"), findingType: field(data, "findingType") as AiFindingType, confidence: Number(field(data, "confidence") || 0), locationText: field(data, "locationText") });
    } catch (submitError) {
      setFieldError(submitError instanceof Error ? submitError.message : "请检查表单内容。")
    }
  };
  return <><form className="entity-form" onSubmit={submit}>{action === "succeed" ? <><fieldset className="form-section"><legend>运行输出</legend><label><span>输出结果(JSON)<em>*</em></span><textarea name="output" rows={8} required defaultValue="{}" /></label><div className="relation-toolbar"><div><strong>输出附件</strong><small>可关联推理报告、标注文件或结果影像</small></div><button className="button secondary" type="button" onClick={() => setOpen(true)}><FileUp aria-hidden="true" />选择输出附件</button></div><div className="relation-chips">{outputs.map((item) => <span key={item.id}><strong>{item.originalName}</strong><button type="button" onClick={() => setOutputs((items) => items.filter((candidate) => candidate.id !== item.id))}>×</button></span>)}</div></fieldset></> : action === "fail" ? <fieldset className="form-section"><legend>失败原因</legend><label><span>错误信息<em>*</em></span><textarea name="errorMessage" rows={5} required /></label></fieldset> : <fieldset className="form-section"><legend>识别成果</legend><div className="form-grid"><label className="field-span"><span>成果标题</span><input name="title" defaultValue={record.title} /></label><label><span>识别类型<em>*</em></span><select name="findingType">{Object.entries(FINDING_TYPES).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><span>置信度<em>*</em></span><input name="confidence" type="number" min="0" max="1" step="0.01" required defaultValue="0.8" /></label><label className="field-span"><span>位置说明</span><input name="locationText" placeholder="可补充具体位置或异常区域" /></label></div></fieldset>}{fieldError && <p className="form-error">{fieldError}</p>}{error && <p className="form-error">{error.message}</p>}<div className="form-actions"><button className="button secondary" type="button" onClick={onCancel}>取消</button><button className="button primary" disabled={pending}>{pending ? "正在提交" : "确认提交"}</button></div></form><AttachmentSelector open={open} selectedIds={outputs.map((item) => item.id)} title="选择推理输出文件" onClose={() => setOpen(false)} onChange={setOutputs} /></>;
}

function RunDetail({ record }: { record: AiInferenceRun }) { return <div className="domain-detail"><section className="detail-group"><h3>任务信息</h3><dl><Fact label="任务编号" value={record.runNo} /><Fact label="状态" value={STATUS_LABELS[record.status]} /><Fact label="模型版本" value={`${record.model?.name || "已失效"} / ${record.model?.version || "-"}`} /><Fact label="部署实例" value={record.deployment?.name || "默认运行环境"} /><Fact label="林班范围" value={record.blocks.map((item) => item.code).join("、")} /><Fact label="提交人" value={record.createdBy} /><Fact label="提交时间" value={formatDate(record.requestedAt)} /><Fact label="运行耗时" value={record.durationMs == null ? "尚未完成" : `${record.durationMs} ms`} /></dl></section><section className="detail-group"><h3>输入与输出</h3><pre>{JSON.stringify({ parameters: record.parameters, output: record.output }, null, 2)}</pre>{record.errorMessage && <p className="form-error">{record.errorMessage}</p>}<div className="maintenance-list">{[...record.inputAttachments, ...record.outputAttachments].map((item) => <article key={item.id}><Database aria-hidden="true" /><div><strong>{item.originalName}</strong><small>{item.sha256.slice(0, 16)}</small><a href={item.downloadUrl || undefined}>下载受控文件</a></div></article>)}</div>{record.findingId && <a className="button secondary" href="/v2/ai/reviews">查看识别复核台账</a>}</section></div>; }
function Summary({ label, value, detail, tone = "" }: { label: string; value: number; detail: string; tone?: string }) { return <div className={tone}><small>{label}</small><strong>{value}</strong><em>{detail}</em></div>; }
function Fact({ label, value }: { label: string; value?: string | null }) { return <div><dt>{label}</dt><dd>{value || "未填写"}</dd></div>; }
function field(data: FormData, name: string) { return String(data.get(name) || "").trim(); }
function jsonField(data: FormData, name: string) { const raw = field(data, name); try { const value = JSON.parse(raw || "{}"); if (!value || Array.isArray(value) || typeof value !== "object") throw new Error(); return value as Record<string, unknown>; } catch { throw new Error(`${name === "output" ? "输出结果" : "推理参数"}必须是 JSON 对象。`); } }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(date); }
function actionTitle(action: ActionKind) { return action === "succeed" ? "登记成功结果" : action === "fail" ? "登记运行失败" : "生成待复核识别成果"; }
async function invalidate(client: ReturnType<typeof useQueryClient>) { await Promise.all([client.invalidateQueries({ queryKey: ["v2-ai-inference-runs"] }), client.invalidateQueries({ queryKey: ["v2-ai-findings"] })]); }
