import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Eye, MapPinned, Pencil, Plus, RefreshCw, RotateCcw, Route, Search, Trash2, Wrench, X } from "lucide-react";
import { type FormEvent, useDeferredValue, useMemo, useState } from "react";

import { api } from "../api/client";
import type { ForestBlockOption, ForestRoadPayload, ForestRoadRecord, RoadClass, RoadCondition, RoadMaintenancePayload, RoadSurface } from "../api/types";
import { ForestBlockSelector } from "../components/ForestBlockSelector";
import { LedgerPagination } from "../components/LedgerPagination";
import { QueryState } from "../components/QueryState";
import { RoadGeometryEditor } from "../components/RoadGeometryEditor";
import { SidePanel } from "../components/SidePanel";
import { hasPermission, useCapabilities } from "../hooks/useCapabilities";

const PAGE_SIZE = 30;
const CLASS_LABELS: Record<RoadClass, string> = { main: "主干道", branch: "支路", operation: "生产作业道", firebreak: "防火通道", footpath: "巡护步道", other: "其他" };
const SURFACE_LABELS: Record<RoadSurface, string> = { paved: "硬化路面", gravel: "砂石路", earth: "土路", boardwalk: "栈道", other: "其他" };
const CONDITION_LABELS: Record<RoadCondition, string> = { good: "良好", fair: "一般", poor: "较差", closed: "封闭" };

export function ForestRoadsPage() {
  const client = useQueryClient(); const capabilities = useCapabilities();
  const [q, setQ] = useState(""); const [roadClass, setRoadClass] = useState(""); const [condition, setCondition] = useState("");
  const [includeDeleted, setIncludeDeleted] = useState(false); const [offset, setOffset] = useState(0);
  const [creating, setCreating] = useState(false); const [selected, setSelected] = useState<ForestRoadRecord | null>(null); const [editing, setEditing] = useState<ForestRoadRecord | null>(null);
  const deferredQ = useDeferredValue(q);
  const ledger = useQuery({ queryKey: ["forest-roads", deferredQ, roadClass, condition, includeDeleted, offset], queryFn: () => api.forestRoads({ q: deferredQ, roadClass, condition, includeDeleted, limit: PAGE_SIZE, offset }), placeholderData: (previous) => previous });
  const permissions = capabilities.data?.permissions; const roles = capabilities.data?.principal.roles;
  const canCreate = hasPermission(permissions, roles, "forest.roads.create"); const canUpdate = hasPermission(permissions, roles, "forest.roads.update"); const canDelete = hasPermission(permissions, roles, "forest.roads.delete"); const canManage = hasPermission(permissions, roles, "forest.roads.manage"); const canMaintain = hasPermission(permissions, roles, "forest.roads.maintain"); const canExport = hasPermission(permissions, roles, "forest.roads.export");
  const invalidate = async () => client.invalidateQueries({ queryKey: ["forest-roads"] });
  const create = useMutation({ mutationFn: api.createForestRoad, onSuccess: async (record) => { setCreating(false); setSelected(record); await invalidate(); } });
  const update = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: Partial<ForestRoadPayload> & { expectedVersion: number } }) => api.updateForestRoad(id, payload), onSuccess: async (record) => { setEditing(null); setSelected(record); await invalidate(); } });
  const remove = useMutation({ mutationFn: ({ id, version }: { id: string; version: number }) => api.deleteForestRoad(id, version), onSuccess: async () => { setSelected(null); await invalidate(); } });
  const restore = useMutation({ mutationFn: api.restoreForestRoad, onSuccess: async (record) => { setSelected(record); await invalidate(); } });
  const maintain = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: RoadMaintenancePayload }) => api.addForestRoadMaintenance(id, payload), onSuccess: async (_, variables) => { const record = await api.forestRoad(variables.id); setSelected(record); await invalidate(); } });
  const items = ledger.data?.items ?? [];
  const metrics = useMemo(() => ({ count: ledger.data?.total ?? 0, length: items.reduce((sum, item) => sum + Number(item.lengthKm || 0), 0), poor: items.filter((item) => item.condition === "poor" || item.condition === "closed").length, linked: items.filter((item) => item.linkedBlockCodes.length).length }), [items, ledger.data?.total]);

  return <div className="standard-page ledger-page forest-roads-page">
    <section className="page-heading ledger-heading"><div><span className="eyebrow">空间资源 / 道路基础设施</span><h1>道路台账</h1><p>登记林区道路真实空间线、等级、路面、路况、责任单位及巡检维修流水，并与正式林班建立关系。</p></div><div className="heading-actions">{canExport && <a className="button secondary" href="/api/v2/roads/export.csv"><Download />导出台账</a>}<button className="button secondary" type="button" onClick={() => ledger.refetch()}><RefreshCw />刷新</button><button className="button primary" type="button" disabled={!canCreate} onClick={() => setCreating(true)}><Plus />新增道路</button></div></section>
    <section className="domain-summary-strip"><Summary label="道路总数" value={metrics.count} detail="正式空间主档" /><Summary label="本页里程" value={metrics.length.toFixed(2)} detail="公里" /><Summary label="较差/封闭" value={metrics.poor} detail="需要处置" tone={metrics.poor ? "warning" : ""} /><Summary label="已关联林班" value={metrics.linked} detail="本页记录" /></section>
    <section className="ledger-shell"><div className="ledger-toolbar domain-ledger-toolbar"><label className="search-field"><Search /><input value={q} onChange={(event) => { setQ(event.target.value); setOffset(0); }} placeholder="搜索道路编号、名称、责任单位" /></label><label className="compact-filter"><span>道路等级</span><select value={roadClass} onChange={(event) => { setRoadClass(event.target.value); setOffset(0); }}><option value="">全部等级</option>{Object.entries(CLASS_LABELS).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label className="compact-filter"><span>当前路况</span><select value={condition} onChange={(event) => { setCondition(event.target.value); setOffset(0); }}><option value="">全部路况</option>{Object.entries(CONDITION_LABELS).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label>{canManage && <label className="toggle-filter"><input type="checkbox" checked={includeDeleted} onChange={(event) => { setIncludeDeleted(event.target.checked); setOffset(0); }} /><span>显示回收站</span></label>}</div>
      <QueryState loading={ledger.isLoading} error={ledger.error}><div className="table-scroll"><table className="ledger-table"><thead><tr><th>道路档案</th><th>等级与路面</th><th>空间规模</th><th>关联林班</th><th>路况与巡检</th><th className="action-column">操作</th></tr></thead><tbody>{items.map((record) => <tr key={record.id} className={record.deletedAt ? "is-deleted" : ""} onClick={() => setSelected(record)}><td><strong>{record.name}</strong><small>{record.roadCode}</small></td><td><strong>{CLASS_LABELS[record.roadClass]}</strong><small>{SURFACE_LABELS[record.surfaceType]}</small></td><td><strong>{Number(record.lengthKm).toFixed(3)} km</strong><small>{record.widthM == null ? "宽度待补" : `均宽 ${record.widthM} m`}</small></td><td><strong>{record.linkedBlockCodes.join("、") || "未关联"}</strong><small>{record.responsibleUnit || "责任单位待补"}</small></td><td><span className={`status-badge road-${record.condition}`}>{record.deletedAt ? "已删除" : CONDITION_LABELS[record.condition]}</span><small>{record.lastInspectedOn || "尚未巡检"}</small></td><td className="action-column"><div className="row-actions"><button className="icon-button" type="button" title="查看" onClick={(event) => { event.stopPropagation(); setSelected(record); }}><Eye /></button>{record.deletedAt ? <button className="icon-button" type="button" title="恢复" disabled={!canManage} onClick={(event) => { event.stopPropagation(); restore.mutate(record.id); }}><RotateCcw /></button> : <><button className="icon-button" type="button" title="编辑" disabled={!canUpdate} onClick={(event) => { event.stopPropagation(); setEditing(record); }}><Pencil /></button><button className="icon-button danger-copy" type="button" title="删除" disabled={!canDelete} onClick={(event) => { event.stopPropagation(); if (window.confirm(`确认将“${record.name}”移入回收站吗？`)) remove.mutate({ id: record.id, version: record.version }); }}><Trash2 /></button></>}</div></td></tr>)}{!ledger.isLoading && !items.length && <tr><td colSpan={6}><div className="table-empty"><Route /><strong>当前没有道路空间主档</strong><p>点击“新增道路”，在真实底图上绘制路线并关联林班。</p></div></td></tr>}</tbody></table></div></QueryState><LedgerPagination total={ledger.data?.total ?? 0} limit={PAGE_SIZE} offset={offset} onPage={setOffset} /></section>
    <SidePanel wide open={creating} eyebrow="道路空间主档" title="新增道路" onClose={() => !create.isPending && setCreating(false)}><RoadForm pending={create.isPending} error={create.error} onCancel={() => setCreating(false)} onSubmit={(payload) => create.mutate(payload)} /></SidePanel>
    <SidePanel wide open={Boolean(editing)} eyebrow="道路空间主档" title={`编辑 ${editing?.name || "道路"}`} onClose={() => !update.isPending && setEditing(null)}>{editing && <RoadForm initial={editing} pending={update.isPending} error={update.error} onCancel={() => setEditing(null)} onSubmit={(payload) => update.mutate({ id: editing.id, payload: { ...payload, roadCode: undefined, expectedVersion: editing.version } })} />}</SidePanel>
    <SidePanel wide open={Boolean(selected)} eyebrow="道路档案详情" title={selected?.name || "道路详情"} onClose={() => setSelected(null)}>{selected && <RoadDetail record={selected} canMaintain={canMaintain && !selected.deletedAt} pending={maintain.isPending} error={maintain.error} onMaintain={(payload) => maintain.mutate({ id: selected.id, payload })} />}</SidePanel>
  </div>;
}

function RoadForm({ initial, pending, error, onCancel, onSubmit }: { initial?: ForestRoadRecord; pending: boolean; error: Error | null; onCancel: () => void; onSubmit: (payload: ForestRoadPayload) => void }) {
  const [blocks, setBlocks] = useState<ForestBlockOption[]>(initial?.linkedBlockCodes.map((code) => ({ id: code, code, name: code, location: "", areaMu: null, hasGeometry: false, riskLevel: null })) ?? []);
  const [geometry, setGeometry] = useState<ForestRoadRecord["geometry"] | null>(initial?.geometry ?? null); const [selectorOpen, setSelectorOpen] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!geometry || !blocks.length) return; const data = new FormData(event.currentTarget); const optionalNumber = (name: string) => { const value = String(data.get(name) || ""); return value ? Number(value) : null; }; onSubmit({ roadCode: String(data.get("roadCode") || "").trim(), name: String(data.get("name") || "").trim(), roadClass: String(data.get("roadClass")) as RoadClass, surfaceType: String(data.get("surfaceType")) as RoadSurface, condition: String(data.get("condition")) as RoadCondition, widthM: optionalNumber("widthM"), lengthKm: optionalNumber("lengthKm"), linkedBlockCodes: blocks.map((item) => item.code), responsibleUnit: String(data.get("responsibleUnit") || "").trim(), lastInspectedOn: String(data.get("lastInspectedOn") || ""), notes: String(data.get("notes") || "").trim(), geometry }); };
  return <><form className="entity-form" onSubmit={submit}><fieldset className="form-section"><legend>道路主档</legend><div className="form-grid"><label><span>道路编号<em>*</em></span><input name="roadCode" required readOnly={Boolean(initial)} defaultValue={initial?.roadCode} /></label><label><span>道路名称<em>*</em></span><input name="name" required defaultValue={initial?.name} /></label><label><span>道路等级</span><select name="roadClass" defaultValue={initial?.roadClass || "operation"}>{Object.entries(CLASS_LABELS).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label><span>路面类型</span><select name="surfaceType" defaultValue={initial?.surfaceType || "earth"}>{Object.entries(SURFACE_LABELS).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label><span>当前路况</span><select name="condition" defaultValue={initial?.condition || "fair"}>{Object.entries(CONDITION_LABELS).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label><span>平均宽度（m）</span><input name="widthM" type="number" min="0" step="0.01" defaultValue={initial?.widthM ?? ""} /></label><label><span>核定长度（km）</span><input name="lengthKm" type="number" min="0" step="0.001" defaultValue={initial?.lengthKm ?? ""} /></label><label><span>责任单位</span><input name="responsibleUnit" defaultValue={initial?.responsibleUnit} /></label><label><span>最近巡检日期</span><input name="lastInspectedOn" type="date" defaultValue={initial?.lastInspectedOn} /></label><label className="field-span"><span>备注</span><textarea name="notes" rows={3} defaultValue={initial?.notes} /></label></div></fieldset><fieldset className="form-section"><legend>关联林班<em>*</em></legend><div className="relation-toolbar"><p>道路至少关联一个正式林班；跨林班路线必须属于同一县级行政区。</p><button className="button secondary" type="button" onClick={() => setSelectorOpen(true)}><MapPinned />选择林班</button></div><div className="relation-chips">{blocks.map((block) => <span key={block.code}><strong>{block.name}</strong><small>{block.code}</small><button type="button" onClick={() => setBlocks((items) => items.filter((item) => item.code !== block.code))}><X /></button></span>)}</div></fieldset><fieldset className="form-section"><legend>道路空间线<em>*</em></legend><RoadGeometryEditor value={geometry} onChange={setGeometry} /></fieldset>{!blocks.length && <p className="form-error">请至少选择一个正式林班。</p>}{!geometry && <p className="form-error">请绘制或导入道路空间线。</p>}{error && <p className="form-error">{error.message}</p>}<div className="form-actions"><button className="button secondary" type="button" onClick={onCancel}>取消</button><button className="button primary" disabled={pending || !geometry || !blocks.length}>{pending ? "正在保存" : "保存道路"}</button></div></form><ForestBlockSelector open={selectorOpen} onClose={() => setSelectorOpen(false)} onSelect={(block) => setBlocks((items) => items.some((item) => item.code === block.code) ? items : [...items, block])} /></>;
}

function RoadDetail({ record, canMaintain, pending, error, onMaintain }: { record: ForestRoadRecord; canMaintain: boolean; pending: boolean; error: Error | null; onMaintain: (payload: RoadMaintenancePayload) => void }) {
  const detail = useQuery({ queryKey: ["forest-road", record.id, record.version], queryFn: () => api.forestRoad(record.id), initialData: record }); const current = detail.data;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const cost = String(data.get("costYuan") || ""); onMaintain({ maintenanceType: String(data.get("maintenanceType")) as RoadMaintenancePayload["maintenanceType"], occurredOn: String(data.get("occurredOn")), conditionAfter: (String(data.get("conditionAfter")) || null) as RoadCondition | null, costYuan: cost ? Number(cost) : null, responsibleUnit: String(data.get("responsibleUnit") || ""), note: String(data.get("note") || "") }); event.currentTarget.reset(); };
  return <div className="domain-detail"><section className="detail-group"><h3>道路信息</h3><dl><Fact label="道路编号" value={current.roadCode} /><Fact label="道路等级" value={CLASS_LABELS[current.roadClass]} /><Fact label="路面" value={SURFACE_LABELS[current.surfaceType]} /><Fact label="当前路况" value={CONDITION_LABELS[current.condition]} /><Fact label="长度" value={`${Number(current.lengthKm).toFixed(3)} km`} /><Fact label="平均宽度" value={current.widthM == null ? "待补" : `${current.widthM} m`} /><Fact label="责任单位" value={current.responsibleUnit} /><Fact label="最近巡检" value={current.lastInspectedOn} /></dl><div className="relation-chips read-only">{current.linkedBlockCodes.map((code) => <span key={code}><strong>{code}</strong><small>正式关联林班</small></span>)}</div></section><section className="detail-group"><h3>巡检维护记录</h3>{current.maintenance?.length ? <div className="maintenance-list">{current.maintenance.map((item) => <article key={item.id}><Wrench /><div><strong>{item.occurredOn} · {item.maintenanceType}</strong><small>{item.responsibleUnit || "责任单位待补"}{item.costYuan != null ? ` · ¥${item.costYuan}` : ""}</small><p>{item.note || "无补充说明"}</p></div></article>)}</div> : <p className="roadmap-empty">暂无巡检维护记录</p>}</section>{canMaintain && <section className="domain-action-card"><form onSubmit={submit}><header><span>道路养护</span><h3>登记巡检或维修</h3></header><div className="form-grid"><label><span>记录类型</span><select name="maintenanceType"><option value="inspection">巡检</option><option value="repair">维修</option><option value="clearing">清障</option><option value="drainage">排水维护</option><option value="closure">封闭</option><option value="reopen">恢复通行</option></select></label><label><span>发生日期</span><input name="occurredOn" type="date" required /></label><label><span>处置后路况</span><select name="conditionAfter"><option value="">保持原状</option>{Object.entries(CONDITION_LABELS).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label><span>费用（元）</span><input name="costYuan" type="number" min="0" step="0.01" /></label><label><span>责任单位</span><input name="responsibleUnit" /></label><label className="field-span"><span>记录说明</span><textarea name="note" rows={3} /></label></div><div className="form-actions"><button className="button primary" disabled={pending}>登记记录</button></div></form></section>}{error && <p className="form-error">{error.message}</p>}</div>;
}

function Summary({ label, value, detail, tone = "" }: { label: string; value: string | number; detail: string; tone?: string }) { return <div className={tone}><small>{label}</small><strong>{value}</strong><em>{detail}</em></div>; }
function Fact({ label, value }: { label: string; value?: string | null }) { return <div><dt>{label}</dt><dd>{value || "未填写"}</dd></div>; }
