import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, CheckCircle2, FileKey2, GitBranch, LockKeyhole, Plus, ShieldCheck, UsersRound } from "lucide-react";
import { type FormEvent, useState } from "react";

import { api } from "../api/client";
import { SidePanel } from "../components/SidePanel";

export function GovernancePage() {
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false);
  const baseline = useQuery({ queryKey: ["requirements-baseline"], queryFn: api.requirementsBaseline });
  const requests = useQuery({ queryKey: ["access-requests"], queryFn: api.accessRequests });
  const retention = useQuery({ queryKey: ["audit-retention"], queryFn: api.auditRetention });
  return <div className="standard-page ledger-page roadmap-page"><section className="page-heading ledger-heading"><div><span className="eyebrow">系统治理 / BASE-01 · SYS-01</span><h1>范围、权限与审计治理</h1><p>冻结增量开发基线，保持 11 类角色与县级隔离，管理跨区查询审批及至少 6 个月审计保留。</p></div><button className="button primary" type="button" onClick={() => setOpen(true)}><Plus />申请跨区查询</button></section>
    <section className="metric-strip roadmap-metrics"><Metric icon={GitBranch} label="代码基线" value={baseline.data?.baselineCommit || "—"} unit="commit" /><Metric icon={UsersRound} label="角色预置" value={baseline.data?.roleCount ?? 0} unit="类" /><Metric icon={FileKey2} label="跨区申请" value={requests.data?.total ?? 0} unit="项" /><Metric icon={Archive} label="最低留存" value={retention.data?.minimumRetentionMonths ?? 6} unit="个月" /></section>
    <section className="roadmap-grid two-columns"><article className="roadmap-card span-two"><header><div><span>需求映射</span><h2>V2 后续需求包交付基线</h2></div><small>范围版本 {baseline.data?.scopeVersion}</small></header><div className="requirement-package-grid">{baseline.data?.packages.map((item) => <div key={item.key}><span className={`priority ${item.priority.startsWith("P0") ? "critical" : ""}`}>{item.priority}</span><strong>{item.key}</strong><small>{delivery(item.delivery)}</small><Status value={item.status} /></div>)}</div><footer className="roadmap-note"><CheckCircle2 />{baseline.data?.nonDuplicateRule}</footer></article>
      <article className="roadmap-card"><header><div><span>临时授权</span><h2>跨区查询申请</h2></div><LockKeyhole /></header><div className="roadmap-list">{requests.data?.items.slice(0, 8).map((item) => <div key={item.id}><span><strong>{(item.requestedAreaCodes as string[] | undefined)?.join("、") || "未指定区域"}</strong><small>{String(item.requestedBy)} · 至 {String(item.expiresAt)}</small></span><Status value={String(item.status)} /></div>)}{!requests.data?.items.length && <p className="roadmap-empty">尚无跨区查询申请</p>}</div></article>
      <article className="roadmap-card"><header><div><span>合规留痕</span><h2>审计保留策略</h2></div><ShieldCheck /></header><div className="roadmap-list">{retention.data?.items.map((item) => <div key={item.id}><span><strong>{(item.eventCategories as string[] | undefined)?.join("、")}</strong><small>{String(item.archiveStorageRef)}</small></span><b>{String(item.retentionMonths)} 个月</b></div>)}{!retention.data?.items.length && <p className="roadmap-empty">尚未配置归档策略；生产启用前必须覆盖登录、查询、审批、导出、模型与飞行操作。</p>}</div></article>
    </section>{baseline.data && <p className="governance-disclaimer">{baseline.data.externalAcceptanceDisclaimer}</p>}<AccessPanel open={open} close={() => setOpen(false)} saved={async () => { setOpen(false); await queryClient.invalidateQueries({ queryKey: ["access-requests"] }); }} /></div>;
}

function AccessPanel({ open, close, saved }: { open: boolean; close: () => void; saved: () => Promise<void> }) { const mutation = useMutation({ mutationFn: (form: HTMLFormElement) => { const data = new FormData(form); const value = (name: string) => String(data.get(name) || "").trim(); return api.createAccessRequest({ requestedAreaCodes: value("requestedAreaCodes").split(/[,，\s]+/).filter(Boolean), reason: value("reason"), expiresAt: new Date(value("expiresAt")).toISOString(), dataCategories: value("dataCategories").split(/[,，\s]+/).filter(Boolean), operations: ["view"] }); }, onSuccess: saved }); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); mutation.mutate(event.currentTarget); }; return <SidePanel open={open} eyebrow="县级隔离" title="申请跨区查询" onClose={close}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label className="field-span"><span>区域代码（逗号分隔）</span><input name="requestedAreaCodes" required /></label><label className="field-span"><span>数据类别</span><input name="dataCategories" placeholder="资源、采伐、成本" /></label><label className="field-span"><span>授权截止时间</span><input name="expiresAt" type="datetime-local" required /></label><label className="field-span"><span>申请原因</span><textarea name="reason" minLength={5} rows={5} required /></label></div>{mutation.error && <p className="form-error">{mutation.error.message}</p>}<div className="form-actions"><button className="button secondary" type="button" onClick={close}>取消</button><button className="button primary" disabled={mutation.isPending}>提交申请</button></div></form></SidePanel>; }
function Metric({ icon: Icon, label, value, unit }: { icon: typeof GitBranch; label: string; value: string | number; unit: string }) { return <div className="metric"><Icon /><span><small>{label}</small><strong>{value}</strong><em>{unit}</em></span></div>; }
function Status({ value }: { value: string }) { const tone = ["implemented", "approved", "active"].includes(value) ? "success" : ["rejected", "revoked"].includes(value) ? "danger" : "warning"; const labels: Record<string, string> = { implemented: "已实现", "integration-ready": "待实联", pending: "待审批", approved: "已批准", rejected: "已驳回", revoked: "已撤销", active: "启用" }; return <span className={`status-badge ${tone}`}>{labels[value] || value}</span>; }
function delivery(value: string) { return ({ baseline: "范围与兼容基线", software: "软件闭环", "software-and-model": "软件 + 模型联调", "software-and-device": "软件 + 设备联调", "model-integration": "真实模型联调", "supplier-integration": "供应商实联" } as Record<string, string>)[value] || value; }
