import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Antenna, BrainCircuit, Cable, CircleDot, Plane, Plus, RadioTower, Send, Video } from "lucide-react";
import { type FormEvent, useState } from "react";

import { api } from "../api/client";
import { SidePanel } from "../components/SidePanel";

const protocols = ["mqtt", "http", "onvif", "rtsp", "gb28181", "flight-control", "model-runtime"];

export function IntegrationHubPage() {
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false);
  const adapters = useQuery({ queryKey: ["integration-adapters"], queryFn: api.integrationAdapters });
  const telemetry = useQuery({ queryKey: ["iot-telemetry"], queryFn: api.telemetryLedger });
  const commands = useQuery({ queryKey: ["iot-commands"], queryFn: api.commandLedger });
  const deployments = useQuery({ queryKey: ["model-deployments"], queryFn: api.modelDeployments });
  const active = adapters.data?.items.filter((item) => item.enabled).length ?? 0;
  return <div className="standard-page ledger-page roadmap-page"><section className="page-heading ledger-heading"><div><span className="eyebrow">供应商联调 / AI-01 · IOT-01</span><h1>集成与联调中心</h1><p>统一管理遥测、视频、飞控和模型运行时适配器；“集成就绪”不代表实机或生产精度已经验收。</p></div><button className="button primary" type="button" onClick={() => setOpen(true)}><Plus />配置适配器</button></section>
    <section className="metric-strip roadmap-metrics"><Metric icon={Cable} label="协议适配器" value={adapters.data?.total ?? 0} unit="个" /><Metric icon={RadioTower} label="已启用" value={active} unit="个" /><Metric icon={Antenna} label="遥测事件" value={telemetry.data?.total ?? 0} unit="条" /><Metric icon={BrainCircuit} label="模型部署" value={deployments.data?.total ?? 0} unit="项" /></section>
    <section className="integration-readiness" aria-label="协议就绪矩阵">{protocols.map((protocol) => { const adapter = adapters.data?.items.find((item) => item.adapterType === protocol); return <article className={adapter?.enabled ? "ready" : ""} key={protocol}><CircleDot /><span><strong>{protocol.toUpperCase()}</strong><small>{adapter?.enabled ? "已启用 · 等待/进行实机验收" : adapter ? "已配置未启用" : "待供应商协议"}</small></span><Status value={adapter?.enabled ? "ready" : adapter ? "configured" : "missing"} /></article>; })}</section>
    <section className="roadmap-grid two-columns"><article className="roadmap-card"><header><div><span>标准遥测事件</span><h2>设备数据质量</h2></div><Antenna /></header><div className="roadmap-list">{telemetry.data?.items.slice(0, 8).map((item) => <div key={item.id}><span><strong>{String(item.deviceId)}</strong><small>{String(item.collectedAt)} · {String(item.protocol)}</small></span><Status value={String(item.qualityStatus || "valid")} /></div>)}{!telemetry.data?.items.length && <p className="roadmap-empty">尚无真实遥测回调</p>}</div></article>
      <article className="roadmap-card"><header><div><span>异步控制</span><h2>命令与回执</h2></div><Send /></header><div className="roadmap-list">{commands.data?.items.slice(0, 8).map((item) => <div key={item.id}><span><strong>{String(item.commandType)}</strong><small>{String(item.deviceId)} · {String(item.sentAt)}</small></span><Status value={String(item.status)} /></div>)}{!commands.data?.items.length && <p className="roadmap-empty">尚未发送设备或返航命令</p>}</div></article>
      <article className="roadmap-card"><header><div><span>视频协议</span><h2>真实码流门禁</h2></div><Video /></header><p className="roadmap-copy">仅当 ONVIF、RTSP 或 GB28181 适配器启用后，驾驶舱才开放视频会商。平台最多创建 8 路监控会话，不再用占位视频冒充真实码流。</p></article>
      <article className="roadmap-card"><header><div><span>飞控与模型</span><h2>联调责任边界</h2></div><Plane /></header><p className="roadmap-copy">航线先做禁飞区校验；控制命令使用发送、回执、失败、超时状态。六类模型通过不可变发布版本、灰度部署、精度报告和回滚链路接入。</p></article></section>
    <AdapterPanel open={open} close={() => setOpen(false)} saved={async () => { setOpen(false); await queryClient.invalidateQueries({ queryKey: ["integration-adapters"] }); }} />
  </div>;
}

function AdapterPanel({ open, close, saved }: { open: boolean; close: () => void; saved: () => Promise<void> }) { const mutation = useMutation({ mutationFn: (form: HTMLFormElement) => { const data = new FormData(form); const value = (name: string) => String(data.get(name) || "").trim(); return api.createIntegrationAdapter({ adapterType: value("adapterType"), name: value("name"), endpoint: value("endpoint"), vendor: value("vendor"), credentialRef: value("credentialRef"), enabled: data.get("enabled") === "on", settings: {} }); }, onSuccess: saved }); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); mutation.mutate(event.currentTarget); }; return <SidePanel open={open} eyebrow="供应商协议" title="配置集成适配器" onClose={close}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label><span>协议类型</span><select name="adapterType">{protocols.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>适配器名称</span><input name="name" required /></label><label className="field-span"><span>服务端点</span><input name="endpoint" required placeholder="https:// 或 mqtt://" /></label><label><span>供应商</span><input name="vendor" /></label><label><span>凭据引用</span><input name="credentialRef" placeholder="secret://...（不直接填写密钥）" /></label><label className="check-row field-span"><input type="checkbox" name="enabled" /><span>启用适配器</span></label></div>{mutation.error && <p className="form-error">{mutation.error.message}</p>}<div className="form-actions"><button className="button secondary" type="button" onClick={close}>取消</button><button className="button primary" disabled={mutation.isPending}>保存配置</button></div></form></SidePanel>; }
function Metric({ icon: Icon, label, value, unit }: { icon: typeof Cable; label: string; value: number; unit: string }) { return <div className="metric"><Icon /><span><small>{label}</small><strong>{value}</strong><em>{unit}</em></span></div>; }
function Status({ value }: { value: string }) { const tone = ["ready", "valid", "acknowledged", "active"].includes(value) ? "success" : ["failed", "timed_out", "missing"].includes(value) ? "danger" : "warning"; const labels: Record<string, string> = { ready: "就绪", configured: "已配置", missing: "待接入", valid: "有效", warning: "需复核", sent: "已发送", acknowledged: "已回执", failed: "失败", timed_out: "超时", active: "运行中" }; return <span className={`status-badge ${tone}`}>{labels[value] || value}</span>; }
