import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, BookOpenCheck, Building2, GraduationCap, HardHat, Plus } from "lucide-react";
import { type FormEvent, type ReactNode, useState } from "react";

import { api } from "../api/client";
import { SidePanel } from "../components/SidePanel";

type Panel = "company" | "course" | null;

export function WorkforceDevelopmentPage() {
  const queryClient = useQueryClient(); const [panel, setPanel] = useState<Panel>(null);
  const companies = useQuery({ queryKey: ["labor-companies"], queryFn: api.laborCompanies });
  const courses = useQuery({ queryKey: ["training-courses"], queryFn: api.trainingCourses });
  const certificates = useQuery({ queryKey: ["training-certificates"], queryFn: api.trainingCertificates });
  return <div className="standard-page ledger-page roadmap-page"><section className="page-heading ledger-heading"><div><span className="eyebrow">劳务与安全 / LAB-01</span><h1>劳务培训与资质</h1><p>管理劳务公司、合同模板、一人一码、安全帽绑定、课程题库、考试与证书到期。</p></div><div className="heading-actions"><button className="button secondary" type="button" onClick={() => setPanel("company")}><Building2 />新增劳务公司</button><button className="button primary" type="button" onClick={() => setPanel("course")}><Plus />发布课程</button></div></section>
    <section className="metric-strip roadmap-metrics"><Metric icon={Building2} label="劳务公司" value={companies.data?.total ?? 0} unit="家" /><Metric icon={BookOpenCheck} label="培训课程" value={courses.data?.total ?? 0} unit="门" /><Metric icon={BadgeCheck} label="有效证书" value={certificates.data?.items.filter((item) => item.status === "valid").length ?? 0} unit="本" /><Metric icon={HardHat} label="智能考勤" value="三项核验" unit="安全帽·GPS·围栏" /></section>
    <section className="roadmap-grid two-columns"><article className="roadmap-card"><header><div><span>主体档案</span><h2>劳务公司</h2></div><Building2 /></header><div className="roadmap-list">{companies.data?.items.map((item) => <div key={item.id}><span><strong>{String(item.name)}</strong><small>{String(item.unifiedCreditCode)} · {String(item.contactName || "未填联系人")}</small></span><Status value={String(item.status || "active")} /></div>)}{!companies.data?.items.length && <p className="roadmap-empty">尚未建立劳务公司档案</p>}</div></article>
      <article className="roadmap-card"><header><div><span>安全教育</span><h2>课程与考试</h2></div><GraduationCap /></header><div className="roadmap-list">{courses.data?.items.map((item) => <div key={item.id}><span><strong>{String(item.title)}</strong><small>{String(item.category)} · {String(item.durationMinutes)} 分钟</small></span><b>{String(item.passingScore)} 分</b></div>)}{!courses.data?.items.length && <p className="roadmap-empty">尚未发布培训课程</p>}</div></article>
      <article className="roadmap-card span-two"><header><div><span>有效期管理</span><h2>培训证书</h2></div><BadgeCheck /></header><div className="table-scroll"><table className="ledger-table"><thead><tr><th>证书编号</th><th>人员</th><th>课程</th><th>发证日期</th><th>有效期（月）</th><th>状态</th></tr></thead><tbody>{certificates.data?.items.map((item) => <tr key={item.id}><td><strong>{String(item.certificateNo)}</strong></td><td>{String(item.workerId)}</td><td>{String(item.courseId)}</td><td>{String(item.issuedOn)}</td><td>{String(item.validityMonths)}</td><td><Status value={String(item.status)} /></td></tr>)}{!certificates.data?.items.length && <tr><td colSpan={6}><div className="table-empty"><BadgeCheck /><strong>尚无证书</strong><p>考试达到课程及格线后自动生成证书记录。</p></div></td></tr>}</tbody></table></div></article>
    </section><WorkforcePanel panel={panel} close={() => setPanel(null)} saved={async () => { setPanel(null); await queryClient.invalidateQueries({ queryKey: panel === "company" ? ["labor-companies"] : ["training-courses"] }); }} /></div>;
}

function WorkforcePanel({ panel, close, saved }: { panel: Panel; close: () => void; saved: () => Promise<void> }) { const mutation = useMutation({ mutationFn: (form: HTMLFormElement) => { const data = new FormData(form); const value = (name: string) => String(data.get(name) || "").trim(); if (panel === "company") return api.createLaborCompany({ name: value("name"), unifiedCreditCode: value("unifiedCreditCode"), contactName: value("contactName"), contactPhone: value("contactPhone"), licenseExpiresOn: value("licenseExpiresOn") || null }); return api.createTrainingCourse({ title: value("title"), category: value("category"), durationMinutes: Number(value("durationMinutes")), passingScore: Number(value("passingScore")), validityMonths: Number(value("validityMonths")), contentUri: value("contentUri") }); }, onSuccess: saved }); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); mutation.mutate(event.currentTarget); }; return <SidePanel open={Boolean(panel)} eyebrow="劳务与安全" title={panel === "company" ? "新增劳务公司" : "发布培训课程"} onClose={close}><form className="entity-form" onSubmit={submit}><div className="form-grid">{panel === "company" ? <><Field label="公司名称"><input name="name" required /></Field><Field label="统一信用代码"><input name="unifiedCreditCode" required /></Field><Field label="联系人"><input name="contactName" /></Field><Field label="联系电话"><input name="contactPhone" /></Field><Field label="资质到期日"><input name="licenseExpiresOn" type="date" /></Field></> : <><Field label="课程名称"><input name="title" required /></Field><Field label="课程分类"><input name="category" required /></Field><Field label="课程时长（分钟）"><input name="durationMinutes" type="number" min="1" required /></Field><Field label="及格分"><input name="passingScore" type="number" min="0" max="100" defaultValue="80" /></Field><Field label="证书有效期（月）"><input name="validityMonths" type="number" min="1" defaultValue="12" /></Field><Field label="课程内容地址"><input name="contentUri" /></Field></>}</div>{mutation.error && <p className="form-error">{mutation.error.message}</p>}<div className="form-actions"><button className="button secondary" type="button" onClick={close}>取消</button><button className="button primary" disabled={mutation.isPending}>保存</button></div></form></SidePanel>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label><span>{label}</span>{children}</label>; }
function Metric({ icon: Icon, label, value, unit }: { icon: typeof Building2; label: string; value: string | number; unit: string }) { return <div className="metric"><Icon /><span><small>{label}</small><strong>{value}</strong><em>{unit}</em></span></div>; }
function Status({ value }: { value: string }) { return <span className={`status-badge ${value === "active" || value === "valid" || value === "published" ? "success" : "warning"}`}>{({ active: "有效", valid: "有效", published: "已发布" } as Record<string, string>)[value] || value}</span>; }
