plugins {
    id "com.android.application"
}

android {
    namespace "com.zhushan.smartbamboo"
    compileSdk 35

    defaultConfig {
        applicationId "com.zhushan.smartbamboo"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "1.1.0-alpha01"
        def fieldUrl = project.findProperty("SMART_BAMBOO_URL") ?: "https://36.140.138.117:18081/v2/field/mobile"
        buildConfigField "String", "SMART_BAMBOO_URL", "\"${fieldUrl}\""
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation "androidx.core:core:1.15.0"
}
