from __future__ import annotations

from typing import Any


def option(value: str, label: str) -> dict[str, str]:
    return {"value": value, "label": label}


def text_field(
    key: str,
    label: str,
    section: str,
    *,
    required: bool = False,
    input_type: str = "text",
    **metadata: Any,
) -> dict[str, Any]:
    return {
        "key": key,
        "label": label,
        "section": section,
        "inputType": input_type,
        "required": required,
        **metadata,
    }


def number_field(
    key: str,
    label: str,
    section: str,
    *,
    required: bool = False,
    integer: bool = False,
    unit: str = "",
    minimum: float | int | None = 0,
    **metadata: Any,
) -> dict[str, Any]:
    field = text_field(
        key,
        label,
        section,
        required=required,
        input_type="integer" if integer else "number",
        **metadata,
    )
    if unit:
        field["unit"] = unit
    if minimum is not None:
        field["min"] = minimum
    field.setdefault("step", 1 if integer else 0.01)
    return field


def select_field(
    key: str,
    label: str,
    section: str,
    values: list[tuple[str, str]],
    *,
    required: bool = False,
    **metadata: Any,
) -> dict[str, Any]:
    return text_field(
        key,
        label,
        section,
        required=required,
        input_type="select",
        options=[option(value, option_label) for value, option_label in values],
        **metadata,
    )


def relation_field(
    key: str,
    label: str,
    target_module_key: str,
    relation_type: str,
    *,
    section: str = "业务关联",
    required: bool = False,
    multiple: bool = True,
    relation_group: str = "",
    min_group_targets: int = 0,
    **metadata: Any,
) -> dict[str, Any]:
    if relation_group:
        metadata["relationGroup"] = relation_group
    if min_group_targets:
        metadata["minGroupTargets"] = min_group_targets
    return text_field(
        key,
        label,
        section,
        required=required,
        input_type="business-relation",
        referenceEndpoint=f"/api/references/business/{target_module_key}",
        referenceValueKey="id",
        referenceLabelKey="name",
        relationType=relation_type,
        targetModuleKey=target_module_key,
        multiple=multiple,
        **metadata,
    )


def administrative_division_fields(
    *,
    section: str = "行政区划",
    required: bool = True,
    through: str = "village",
) -> list[dict[str, Any]]:
    levels = [
        ("province", "provinceCode", "所属省份", ""),
        ("city", "cityCode", "所属地市", "provinceCode"),
        ("county", "countyCode", "所属区县", "cityCode"),
        ("town", "townCode", "所属乡镇", "countyCode"),
        ("village", "villageCode", "所属村", "townCode"),
    ]
    fields: list[dict[str, Any]] = []
    for level, key, label, parent_field in levels:
        field = text_field(
            key,
            label,
            section,
            required=required,
            input_type="reference",
            referenceEndpoint=f"/api/dictionary-options/administrative-divisions?level={level}",
            referenceValueKey="value",
            referenceLabelKey="fullName",
            referenceDictionaryCode="administrative-divisions",
            referenceLevel=level,
            displayProperty=f"{level}Name",
            multiple=False,
        )
        if parent_field:
            field["parentField"] = parent_field
        fields.append(field)
        if level == through:
            break
    return fields


PHONE_PATTERN = r"^1[3-9]\d{9}$"
UNIFIED_CREDIT_PATTERN = r"^[0-9A-HJ-NPQRTUWXY]{18}$"


FORMAL_BUSINESS_FIELD_SCHEMAS: dict[str, list[dict[str, Any]]] = {
    "cooperatives": [
        text_field(
            "unifiedSocialCreditCode",
            "统一社会信用代码",
            "主体资质",
            required=True,
            minLength=18,
            maxLength=18,
            pattern=UNIFIED_CREDIT_PATTERN,
        ),
        text_field("legalRepresentative", "法定代表人", "主体资质", required=True, maxLength=80),
        text_field(
            "phone",
            "联系电话",
            "主体资质",
            required=True,
            input_type="tel",
            pattern=PHONE_PATTERN,
            maxLength=11,
        ),
        *administrative_division_fields(),
        text_field("address", "详细地址", "行政区划", required=True, input_type="textarea", maxLength=300),
        number_field("memberCount", "成员数量", "经营能力", required=True, integer=True, unit="人"),
        select_field(
            "serviceCapacity",
            "主要服务能力",
            "经营能力",
            [
                ("tending", "竹林抚育"),
                ("harvest", "采伐采笋"),
                ("plant-protection", "植保防治"),
                ("materials", "农资供应"),
                ("marketing", "产销对接"),
                ("comprehensive", "综合服务"),
            ],
            required=True,
        ),
        select_field(
            "operationStatus",
            "经营状态",
            "经营能力",
            [
                ("preparing", "筹备中"),
                ("active", "正常经营"),
                ("paused", "暂停经营"),
                ("closed", "已注销"),
            ],
            required=True,
        ),
        select_field(
            "orderStatus",
            "订单状态",
            "经营能力",
            [
                ("idle", "暂无订单"),
                ("active", "服务中"),
                ("busy", "任务饱和"),
                ("paused", "暂停接单"),
            ],
        ),
        relation_field(
            "memberFarmerIds",
            "成员竹农",
            "farmers",
            "member",
            multiple=True,
        ),
    ],
    "enterprises": [
        text_field(
            "unifiedSocialCreditCode",
            "统一社会信用代码",
            "主体资质",
            required=True,
            minLength=18,
            maxLength=18,
            pattern=UNIFIED_CREDIT_PATTERN,
        ),
        select_field(
            "enterpriseType",
            "企业类型",
            "主体资质",
            [
                ("processor", "加工企业"),
                ("trader", "贸易企业"),
                ("logistics", "物流企业"),
                ("supplier", "农资供应商"),
                ("service", "技术服务企业"),
                ("comprehensive", "综合企业"),
            ],
            required=True,
        ),
        select_field(
            "mainBusiness",
            "主营方向",
            "经营能力",
            [
                ("raw-bamboo", "原竹经营"),
                ("bamboo-shoot", "竹笋经营"),
                ("primary-processing", "竹材初加工"),
                ("deep-processing", "竹制品深加工"),
                ("equipment-service", "设备与技术服务"),
                ("trade-logistics", "贸易与物流"),
                ("comprehensive", "综合经营"),
            ],
            required=True,
        ),
        text_field("contactName", "联系人", "主体资质", required=True, maxLength=80),
        text_field(
            "phone",
            "联系电话",
            "主体资质",
            required=True,
            input_type="tel",
            pattern=PHONE_PATTERN,
            maxLength=11,
        ),
        *administrative_division_fields(),
        text_field("address", "经营地址", "行政区划", required=True, input_type="textarea", maxLength=300),
        number_field(
            "processingCapacityTons",
            "年加工能力",
            "经营能力",
            unit="吨/年",
        ),
        select_field(
            "purchaseStatus",
            "采购状态",
            "经营能力",
            [
                ("planning", "采购计划"),
                ("purchasing", "采购中"),
                ("completed", "已完成"),
                ("paused", "暂停采购"),
            ],
            required=True,
        ),
        select_field(
            "inventoryStatus",
            "库存状态",
            "经营能力",
            [
                ("normal", "库存正常"),
                ("low", "库存偏低"),
                ("high", "库存偏高"),
                ("out", "无库存"),
            ],
            required=True,
        ),
        relation_field(
            "cooperativeIds",
            "合作合作社",
            "cooperatives",
            "partner",
        ),
    ],
    "plant-protection-events": [
        select_field(
            "issueType",
            "问题类型",
            "事件信息",
            [
                ("bamboo-locust", "竹蝗"),
                ("bamboo-shoot-pest", "竹笋害虫"),
                ("bamboo-witch-broom", "竹丛枝病"),
                ("bamboo-rust", "竹锈病"),
                ("rodent-damage", "鼠害"),
                ("other", "其他"),
            ],
            required=True,
        ),
        text_field(
            "riskLevel",
            "风险等级",
            "事件信息",
            required=True,
            input_type="dictionary",
            dictionaryCode="risk-levels",
        ),
        text_field("discoveredAt", "发现时间", "事件信息", required=True, input_type="datetime-local"),
        select_field(
            "detectionSource",
            "发现来源",
            "事件信息",
            [
                ("patrol", "人工巡护"),
                ("drone", "无人机巡检"),
                ("sensor", "物联感知"),
                ("farmer-report", "竹农上报"),
                ("other", "其他来源"),
            ],
            required=True,
        ),
        number_field("affectedAreaMu", "受影响面积", "影响评估", required=True, unit="亩"),
        text_field("treatmentAdvice", "处置建议", "处置闭环", required=True, input_type="textarea", maxLength=1000),
        text_field("closedAt", "闭环时间", "处置闭环", input_type="datetime-local"),
        select_field(
            "handlingStatus",
            "处置状态",
            "处置闭环",
            [
                ("pending", "待处置"),
                ("handling", "处置中"),
                ("resolved", "已处置"),
                ("verified", "已复核"),
            ],
            required=True,
        ),
        relation_field("handlerFarmerIds", "处置竹农", "farmers", "handler"),
        relation_field("handlerCooperativeIds", "处置合作社", "cooperatives", "handler"),
        relation_field("maintenanceTaskIds", "处置任务", "maintenance-tasks", "resolution-task"),
        relation_field("materialIds", "使用农资", "materials", "consumed-material"),
    ],
    "materials": [
        select_field(
            "itemCategory",
            "物资品类",
            "物资信息",
            [
                ("fertilizer", "肥料"),
                ("pesticide", "植保药剂"),
                ("seedling", "苗木"),
                ("tool", "生产工具"),
                ("protective-equipment", "防护用品"),
                ("other", "其他"),
            ],
            required=True,
        ),
        text_field("specification", "规格型号", "物资信息", required=True, maxLength=120),
        text_field(
            "unit",
            "计量单位",
            "物资信息",
            required=True,
            input_type="dictionary",
            dictionaryCode="material-units",
        ),
        text_field("batchNo", "生产/采购批次", "批次库存", required=True, maxLength=80),
        number_field("stock", "库存数量", "批次库存", required=True),
        number_field("warningThreshold", "预警阈值", "批次库存", required=True),
        text_field("expiryDate", "有效期至", "批次库存", input_type="date"),
        text_field("warehouse", "存放仓库", "批次库存", required=True, maxLength=120),
        select_field(
            "usageStage",
            "适用环节",
            "物资信息",
            [
                ("planting", "栽植"),
                ("tending", "抚育"),
                ("fertilizing", "施肥"),
                ("plant-protection", "植保"),
                ("harvesting", "采收"),
                ("transport", "运输"),
                ("general", "通用"),
            ],
            required=True,
        ),
        select_field(
            "inventoryStatus",
            "库存状态",
            "批次库存",
            [
                ("normal", "库存正常"),
                ("warning", "库存预警"),
                ("out", "缺货"),
                ("expired", "已过期"),
            ],
            required=True,
            readOnly=True,
            computed={
                "operation": "stock-status",
                "fields": ["stock", "warningThreshold"],
            },
        ),
        relation_field(
            "supplierEnterpriseIds",
            "供应企业",
            "enterprises",
            "supplier",
            multiple=False,
        ),
    ],
    "policies": [
        text_field("issuingBody", "发文机关", "文件信息", required=True, maxLength=160),
        select_field(
            "policyLevel",
            "政策层级",
            "文件信息",
            [
                ("national", "国家级"),
                ("provincial", "省级"),
                ("municipal", "市级"),
                ("county", "区县级"),
                ("town", "乡镇级"),
            ],
            required=True,
        ),
        select_field(
            "policyType",
            "政策类型",
            "文件信息",
            [
                ("law", "法律法规"),
                ("subsidy", "补贴政策"),
                ("project", "项目申报"),
                ("technical", "技术规范"),
                ("ecological", "生态保护"),
                ("notice", "通知公告"),
            ],
            required=True,
        ),
        text_field("publishDate", "发布日期", "有效期限", required=True, input_type="date"),
        text_field("effectiveDate", "生效日期", "有效期限", required=True, input_type="date"),
        text_field("deadline", "申报截止日期", "有效期限", input_type="date"),
        select_field(
            "target",
            "适用对象",
            "适用范围",
            [
                ("farmer", "竹农"),
                ("cooperative", "合作社"),
                ("enterprise", "竹企"),
                ("village-collective", "村集体"),
                ("operator", "经营主体"),
                ("all", "全部主体"),
            ],
            required=True,
        ),
        text_field("applicationItem", "申报事项", "适用范围", maxLength=200),
        text_field("summary", "政策摘要", "文件内容", required=True, input_type="textarea", maxLength=2000),
        text_field("attachmentUrl", "政策文件地址", "文件内容", input_type="url", maxLength=500),
        select_field(
            "reviewStatus",
            "发布/申报状态",
            "发布管理",
            [
                ("draft", "草稿"),
                ("open", "可申报"),
                ("review", "审核中"),
                ("closed", "已截止"),
                ("expired", "已失效"),
            ],
            required=True,
        ),
    ],
    "stewardship-agreements": [
        select_field(
            "serviceMode",
            "托管模式",
            "协议信息",
            [
                ("full", "全程托管"),
                ("partial", "环节托管"),
                ("order", "订单托管"),
                ("joint", "联合经营"),
            ],
            required=True,
        ),
        text_field("signedDate", "签订日期", "协议期限", required=True, input_type="date"),
        text_field("startDate", "开始日期", "协议期限", required=True, input_type="date"),
        text_field("endDate", "结束日期", "协议期限", required=True, input_type="date"),
        number_field("areaMu", "托管面积", "经营条款", required=True, unit="亩"),
        select_field(
            "feeMode",
            "费用结算方式",
            "经营条款",
            [
                ("fixed", "固定服务费"),
                ("revenue-share", "收益分成"),
                ("cost-plus", "成本加服务费"),
                ("negotiated", "协商结算"),
            ],
            required=True,
        ),
        select_field(
            "performanceStatus",
            "履约状态",
            "履约管理",
            [
                ("pending", "待履约"),
                ("active", "履约中"),
                ("completed", "已完成"),
                ("breached", "违约"),
                ("terminated", "已终止"),
            ],
            required=True,
        ),
        relation_field("ownerFarmerIds", "委托竹农", "farmers", "principal", required=True),
        relation_field(
            "serviceProviderCooperativeIds",
            "受托合作社",
            "cooperatives",
            "service-provider",
            multiple=False,
            relation_group="service-provider",
            min_group_targets=1,
        ),
        relation_field(
            "serviceProviderEnterpriseIds",
            "受托企业",
            "enterprises",
            "service-provider",
            multiple=False,
            relation_group="service-provider",
            min_group_targets=1,
        ),
    ],
    "franchise-bases": [
        *administrative_division_fields(),
        number_field("baseAreaMu", "基地面积", "基地信息", required=True, unit="亩"),
        select_field(
            "serviceLevel",
            "服务等级",
            "基地信息",
            [("A", "A级"), ("B", "B级"), ("C", "C级")],
            required=True,
        ),
        select_field(
            "operationStatus",
            "运营状态",
            "运营管理",
            [
                ("preparing", "筹备中"),
                ("active", "运营中"),
                ("paused", "暂停运营"),
                ("closed", "已关闭"),
            ],
            required=True,
        ),
        relation_field(
            "operatorCooperativeIds",
            "运营合作社",
            "cooperatives",
            "operator",
            multiple=False,
            relation_group="operator",
            min_group_targets=1,
        ),
        relation_field(
            "operatorEnterpriseIds",
            "运营企业",
            "enterprises",
            "operator",
            multiple=False,
            relation_group="operator",
            min_group_targets=1,
        ),
        relation_field("agreementIds", "关联托管协议", "stewardship-agreements", "agreement"),
    ],
    "maintenance-tasks": [
        select_field(
            "taskType",
            "任务类型",
            "任务信息",
            [
                ("patrol", "巡护"),
                ("tending", "抚育"),
                ("fire-prevention", "防火"),
                ("anti-theft", "防盗伐"),
                ("plant-protection", "植保"),
                ("other", "其他"),
            ],
            required=True,
        ),
        select_field(
            "priority",
            "优先级",
            "任务信息",
            [("low", "低"), ("normal", "普通"), ("high", "高"), ("urgent", "紧急")],
            required=True,
        ),
        text_field("plannedStartAt", "计划开始", "任务排期", required=True, input_type="datetime-local"),
        text_field("plannedEndAt", "计划结束", "任务排期", required=True, input_type="datetime-local"),
        text_field("completedAt", "实际完成", "任务排期", input_type="datetime-local"),
        select_field(
            "closureStatus",
            "闭环状态",
            "任务闭环",
            [
                ("pending", "待处理"),
                ("in-progress", "处理中"),
                ("completed", "已完成"),
                ("verified", "已复核"),
                ("canceled", "已取消"),
            ],
            required=True,
        ),
        relation_field(
            "assigneeFarmerIds",
            "责任竹农",
            "farmers",
            "assignee",
            relation_group="assignee",
            min_group_targets=1,
        ),
        relation_field(
            "assigneeCooperativeIds",
            "责任合作社",
            "cooperatives",
            "assignee",
            relation_group="assignee",
            min_group_targets=1,
        ),
        relation_field("equipmentIds", "使用设备", "equipment", "equipment"),
        relation_field("materialIds", "领用农资", "materials", "material"),
    ],
    "work-logs": [
        select_field(
            "workStage",
            "作业环节",
            "作业信息",
            [
                ("harvesting", "采伐"),
                ("shoot-digging", "挖笋"),
                ("fertilizing", "施肥"),
                ("weeding", "除草"),
                ("transport", "运输"),
                ("other", "其他"),
            ],
            required=True,
        ),
        text_field("workDate", "作业日期", "作业信息", required=True, input_type="date"),
        number_field("laborCount", "用工人数", "投入产出", required=True, integer=True, unit="人"),
        number_field("workQuantity", "作业数量", "投入产出", unit="吨/亩"),
        text_field("resultSummary", "作业结果", "作业复核", required=True, input_type="textarea", maxLength=1000),
        relation_field(
            "workerFarmerIds",
            "作业竹农",
            "farmers",
            "worker",
            relation_group="worker",
            min_group_targets=1,
        ),
        relation_field(
            "workerCooperativeIds",
            "作业合作社",
            "cooperatives",
            "worker",
            relation_group="worker",
            min_group_targets=1,
        ),
        relation_field("reviewerFarmerIds", "复核人员", "farmers", "reviewer"),
        relation_field("taskIds", "来源任务", "maintenance-tasks", "task"),
        relation_field("materialIds", "使用农资", "materials", "material"),
    ],
    "drone-tasks": [
        select_field(
            "taskType",
            "任务类型",
            "航飞任务",
            [
                ("mapping", "测绘"),
                ("inspection", "巡检"),
                ("plant-protection", "植保"),
                ("emergency", "应急"),
            ],
            required=True,
        ),
        text_field("routeCode", "航线编号", "航飞任务", required=True, maxLength=100),
        text_field("plannedStartAt", "计划起飞", "任务时间", required=True, input_type="datetime-local"),
        text_field("actualStartAt", "实际起飞", "任务时间", input_type="datetime-local"),
        text_field("actualEndAt", "实际完成", "任务时间", input_type="datetime-local"),
        select_field(
            "resultStatus",
            "成果状态",
            "成果管理",
            [
                ("pending", "待执行"),
                ("flying", "飞行中"),
                ("processing", "成果处理中"),
                ("ready", "成果已入库"),
                ("failed", "任务失败"),
            ],
            required=True,
        ),
        text_field("resultPackageUrl", "成果包地址", "成果管理", input_type="url", maxLength=500),
        relation_field(
            "equipmentIds",
            "执行无人机",
            "equipment",
            "aircraft",
            required=True,
            multiple=False,
        ),
    ],
    "equipment": [
        select_field(
            "deviceType",
            "设备类型",
            "资产信息",
            [
                ("drone", "无人机"),
                ("sensor", "传感器"),
                ("camera", "视频监控"),
                ("positioning", "定位终端"),
                ("other", "其他"),
            ],
            required=True,
        ),
        text_field("deviceCode", "设备编号", "资产信息", required=True, maxLength=100),
        text_field("model", "品牌型号", "资产信息", required=True, maxLength=160),
        text_field("installLocation", "安装/存放位置", "使用信息", maxLength=300),
        text_field("purchaseDate", "购置日期", "使用信息", input_type="date"),
        text_field("maintenanceDueDate", "下次保养日期", "使用信息", input_type="date"),
        select_field(
            "onlineStatus",
            "运行状态",
            "运行监测",
            [
                ("online", "在线"),
                ("offline", "离线"),
                ("maintenance", "检修中"),
                ("retired", "已报废"),
            ],
            required=True,
        ),
        relation_field(
            "ownerCooperativeIds",
            "所属合作社",
            "cooperatives",
            "owner",
            multiple=False,
            relation_group="owner",
            min_group_targets=1,
        ),
        relation_field(
            "ownerEnterpriseIds",
            "所属企业",
            "enterprises",
            "owner",
            multiple=False,
            relation_group="owner",
            min_group_targets=1,
        ),
    ],
    "pest-warnings": [
        select_field(
            "riskType",
            "病虫害类型",
            "预警信息",
            [
                ("bamboo-locust", "竹蝗"),
                ("bamboo-shoot-pest", "竹笋害虫"),
                ("bamboo-witch-broom", "竹丛枝病"),
                ("bamboo-rust", "竹锈病"),
                ("rodent-damage", "鼠害"),
                ("other", "其他"),
            ],
            required=True,
        ),
        text_field(
            "riskLevel",
            "风险等级",
            "预警信息",
            required=True,
            input_type="dictionary",
            dictionaryCode="risk-levels",
        ),
        select_field(
            "detectionSource",
            "监测来源",
            "预警信息",
            [
                ("model", "模型识别"),
                ("drone", "无人机"),
                ("sensor", "物联感知"),
                ("patrol", "人工巡护"),
                ("report", "群众上报"),
            ],
            required=True,
        ),
        text_field("issuedAt", "发布时间", "预警信息", required=True, input_type="datetime-local"),
        number_field("affectedAreaMu", "影响面积", "影响评估", required=True, unit="亩"),
        text_field("treatmentAdvice", "处置建议", "处置复核", required=True, input_type="textarea", maxLength=1000),
        select_field(
            "reviewStatus",
            "复核状态",
            "处置复核",
            [
                ("pending", "待处置"),
                ("handling", "处置中"),
                ("resolved", "已处置"),
                ("verified", "已复核"),
            ],
            required=True,
        ),
        relation_field("eventIds", "转植保事件", "plant-protection-events", "event"),
        relation_field("taskIds", "处置任务", "maintenance-tasks", "task"),
    ],
    "material-services": [
        select_field(
            "serviceType",
            "服务类型",
            "服务申请",
            [
                ("fertilizer", "肥料配送"),
                ("pesticide", "药剂配送"),
                ("tools", "工具设备"),
                ("technical", "技术服务"),
            ],
            required=True,
        ),
        number_field("requestedQuantity", "申请数量", "数量与时间", required=True),
        number_field("deliveredQuantity", "实发数量", "数量与时间"),
        text_field("requestedAt", "申请时间", "数量与时间", required=True, input_type="datetime-local"),
        text_field("deliveryDate", "配送日期", "数量与时间", input_type="date"),
        select_field(
            "deliveryStatus",
            "配送状态",
            "服务闭环",
            [
                ("pending", "待受理"),
                ("preparing", "备货中"),
                ("delivering", "配送中"),
                ("delivered", "已送达"),
                ("canceled", "已取消"),
            ],
            required=True,
        ),
        select_field(
            "feedbackStatus",
            "反馈状态",
            "服务闭环",
            [
                ("pending", "待反馈"),
                ("satisfied", "满意"),
                ("follow-up", "需跟进"),
                ("closed", "已闭环"),
            ],
            required=True,
        ),
        relation_field("materialIds", "申请物资", "materials", "material", required=True),
        relation_field(
            "supplierEnterpriseIds",
            "供应企业",
            "enterprises",
            "supplier",
            multiple=False,
        ),
        relation_field(
            "applicantFarmerIds",
            "申请竹农",
            "farmers",
            "applicant",
            relation_group="applicant",
            min_group_targets=1,
        ),
        relation_field(
            "applicantCooperativeIds",
            "申请合作社",
            "cooperatives",
            "applicant",
            relation_group="applicant",
            min_group_targets=1,
        ),
    ],
    "yield-forecasts": [
        select_field(
            "forecastObject",
            "预测对象",
            "预测对象",
            [
                ("bamboo-timber", "竹材"),
                ("bamboo-shoot", "竹笋"),
                ("understory", "林下经济"),
            ],
            required=True,
        ),
        text_field("forecastPeriod", "预测周期", "预测对象", required=True, input_type="month"),
        select_field(
            "bambooSpecies",
            "竹种",
            "预测对象",
            [
                ("moso", "毛竹"),
                ("lei-bamboo", "雷竹"),
                ("bambusa", "丛生竹"),
                ("mixed", "混合竹种"),
                ("other", "其他"),
            ],
            required=True,
        ),
        number_field("areaMu", "预测面积", "预测结果", required=True, unit="亩"),
        number_field("forecastYield", "预测产量", "预测结果", required=True, unit="吨"),
        text_field("modelName", "模型名称/版本", "模型信息", required=True, maxLength=160),
        number_field("confidence", "置信度", "模型信息", unit="%", minimum=0, max=100, step=0.1),
        select_field(
            "publishStatus",
            "发布状态",
            "发布管理",
            [
                ("draft", "草稿"),
                ("review", "待审核"),
                ("published", "已发布"),
                ("expired", "已过期"),
            ],
            required=True,
        ),
    ],
    "harvest-plans": [
        select_field(
            "harvestType",
            "采挖类型",
            "计划信息",
            [
                ("timber", "竹材采伐"),
                ("shoot", "竹笋采挖"),
                ("tending", "抚育采收"),
            ],
            required=True,
        ),
        text_field("plannedStartDate", "计划开始日期", "计划排期", required=True, input_type="date"),
        text_field("plannedEndDate", "计划结束日期", "计划排期", required=True, input_type="date"),
        number_field("plannedQuantity", "计划数量", "计划产出", required=True, unit="吨"),
        select_field(
            "harvestMethod",
            "采挖方式",
            "计划产出",
            [
                ("manual", "人工"),
                ("mechanical", "机械"),
                ("combined", "人机协同"),
            ],
            required=True,
        ),
        select_field(
            "executionStatus",
            "执行状态",
            "执行管理",
            [
                ("draft", "草稿"),
                ("approved", "已审批"),
                ("in-progress", "执行中"),
                ("completed", "已完成"),
                ("canceled", "已取消"),
            ],
            required=True,
        ),
        relation_field("forecastIds", "依据产量预测", "yield-forecasts", "forecast"),
        relation_field(
            "operatorCooperativeIds",
            "执行合作社",
            "cooperatives",
            "operator",
            relation_group="operator",
            min_group_targets=1,
        ),
        relation_field(
            "operatorEnterpriseIds",
            "执行企业",
            "enterprises",
            "operator",
            relation_group="operator",
            min_group_targets=1,
        ),
        relation_field("equipmentIds", "使用设备", "equipment", "equipment"),
    ],
    "income-estimates": [
        select_field(
            "estimateType",
            "测算类型",
            "测算信息",
            [
                ("gross-income", "经营收入"),
                ("net-income", "净收益"),
                ("cash-flow", "现金流"),
                ("distribution", "主体分成"),
            ],
            required=True,
        ),
        text_field("estimatePeriod", "测算周期", "测算信息", required=True, input_type="month"),
        number_field("expectedIncome", "预计收入", "金额测算", required=True, unit="元"),
        number_field("cost", "预计成本", "金额测算", required=True, unit="元"),
        number_field(
            "netIncome",
            "预计净收益",
            "金额测算",
            unit="元",
            minimum=None,
            readOnly=True,
            computed={
                "operation": "subtract",
                "fields": ["expectedIncome", "cost"],
                "precision": 2,
            },
        ),
        text_field("assumptions", "测算假设与口径", "测算说明", required=True, input_type="textarea", maxLength=1500),
        select_field(
            "reviewStatus",
            "审核状态",
            "发布管理",
            [
                ("draft", "草稿"),
                ("review", "待审核"),
                ("approved", "已确认"),
                ("rejected", "已退回"),
            ],
            required=True,
        ),
        relation_field("harvestPlanIds", "关联采挖计划", "harvest-plans", "harvest-plan"),
        relation_field(
            "cooperativeIds",
            "测算合作社",
            "cooperatives",
            "subject",
            relation_group="subject",
            min_group_targets=1,
        ),
        relation_field(
            "enterpriseIds",
            "测算企业",
            "enterprises",
            "subject",
            relation_group="subject",
            min_group_targets=1,
        ),
    ],
    "performance-dashboards": [
        select_field(
            "metricType",
            "指标类型",
            "指标定义",
            [
                ("maintenance", "管护绩效"),
                ("operation", "经营绩效"),
                ("organization", "主体绩效"),
            ],
            required=True,
        ),
        text_field(
            "coverage",
            "覆盖区域",
            "指标定义",
            input_type="multi-reference",
            referenceEndpoint="/api/dictionary-options/administrative-divisions",
            referenceValueKey="value",
            referenceLabelKey="fullName",
            multiple=True,
        ),
        text_field("metricCaliber", "指标口径", "指标定义", required=True, input_type="textarea", maxLength=1500),
        number_field("metricValue", "指标值", "指标结果", required=True, minimum=None),
        text_field("metricPeriod", "统计周期", "指标结果", required=True, input_type="month"),
        select_field(
            "publishStatus",
            "发布状态",
            "发布管理",
            [
                ("draft", "草稿"),
                ("review", "待审核"),
                ("published", "已发布"),
                ("offline", "已下线"),
            ],
            required=True,
        ),
        relation_field(
            "ownerCooperativeIds",
            "责任合作社",
            "cooperatives",
            "owner",
            relation_group="owner",
            min_group_targets=1,
        ),
        relation_field(
            "ownerEnterpriseIds",
            "责任企业",
            "enterprises",
            "owner",
            relation_group="owner",
            min_group_targets=1,
        ),
    ],
    "carbon-estimates": [
        select_field(
            "accountingType",
            "核算类型",
            "核算信息",
            [
                ("stock", "碳储量"),
                ("increment", "碳汇增量"),
                ("project", "项目减排量"),
            ],
            required=True,
        ),
        text_field("projectBoundary", "项目边界说明", "核算信息", required=True, input_type="textarea", maxLength=1500),
        text_field("accountingStartDate", "核算开始日期", "核算周期", required=True, input_type="date"),
        text_field("accountingEndDate", "核算结束日期", "核算周期", required=True, input_type="date"),
        number_field("carbonStock", "碳储量/减排量", "核算结果", required=True, unit="tCO2e"),
        number_field("carbonIncrement", "碳汇增量", "核算结果", unit="tCO2e"),
        text_field("methodology", "核算方法学", "核证信息", required=True, maxLength=300),
        text_field("verifier", "核证机构/人员", "核证信息", maxLength=160),
        select_field(
            "verificationStatus",
            "核证状态",
            "核证信息",
            [
                ("calculating", "测算中"),
                ("review", "待复核"),
                ("verified", "已核证"),
                ("rejected", "未通过"),
            ],
            required=True,
        ),
    ],
    "trade-matches": [
        select_field(
            "tradeType",
            "供需类型",
            "交易信息",
            [("supply", "供应"), ("demand", "采购需求")],
            required=True,
        ),
        select_field(
            "productType",
            "产品品类",
            "交易信息",
            [
                ("bamboo-timber", "竹材"),
                ("bamboo-shoot", "竹笋"),
                ("processed", "竹加工品"),
                ("understory", "林下产品"),
            ],
            required=True,
        ),
        select_field(
            "qualityGrade",
            "质量等级",
            "交易信息",
            [("premium", "优等"), ("standard", "标准"), ("ordinary", "普通"), ("other", "其他")],
            required=True,
        ),
        number_field("quantity", "交易数量", "价格交付", required=True),
        text_field(
            "unit",
            "计量单位",
            "价格交付",
            required=True,
            input_type="dictionary",
            dictionaryCode="material-units",
        ),
        number_field("unitPrice", "意向单价", "价格交付", required=True, unit="元"),
        text_field("deliveryStartDate", "交付开始日期", "价格交付", input_type="date"),
        text_field("deliveryEndDate", "交付结束日期", "价格交付", input_type="date"),
        select_field(
            "matchStatus",
            "撮合状态",
            "撮合进度",
            [
                ("pending", "待撮合"),
                ("negotiating", "洽谈中"),
                ("matched", "已撮合"),
                ("closed", "已成交"),
                ("canceled", "已取消"),
            ],
            required=True,
        ),
        relation_field(
            "buyerEnterpriseIds",
            "采购企业",
            "enterprises",
            "buyer",
            required=True,
        ),
        relation_field(
            "sellerCooperativeIds",
            "供应合作社",
            "cooperatives",
            "seller",
            relation_group="seller",
            min_group_targets=1,
        ),
        relation_field(
            "sellerEnterpriseIds",
            "供应企业",
            "enterprises",
            "seller",
            relation_group="seller",
            min_group_targets=1,
        ),
    ],
    "logistics-traces": [
        text_field("batchNo", "溯源批次", "物流批次", required=True, maxLength=100),
        text_field("vehicleNo", "车牌号", "承运信息", required=True, maxLength=30),
        text_field("driverName", "司机姓名", "承运信息", required=True, maxLength=80),
        text_field(
            "driverPhone",
            "司机电话",
            "承运信息",
            required=True,
            input_type="tel",
            pattern=PHONE_PATTERN,
            maxLength=11,
        ),
        text_field("currentNode", "当前物流节点", "流转状态", required=True, maxLength=160),
        number_field("quantity", "流转数量", "物流批次", required=True),
        text_field("departureAt", "发运时间", "流转状态", required=True, input_type="datetime-local"),
        text_field("arrivalAt", "到达时间", "流转状态", input_type="datetime-local"),
        select_field(
            "logisticsStatus",
            "物流状态",
            "流转状态",
            [
                ("collected", "已采收"),
                ("in-transit", "运输中"),
                ("warehoused", "已入库"),
                ("delivered", "已交付"),
                ("exception", "异常"),
            ],
            required=True,
        ),
        relation_field(
            "carrierEnterpriseIds",
            "承运企业",
            "enterprises",
            "carrier",
            required=True,
            multiple=False,
        ),
        relation_field("tradeMatchIds", "关联交易单", "trade-matches", "trade-order"),
    ],
    "product-qrcodes": [
        text_field("qrCode", "二维码编号", "码信息", readOnly=True),
        select_field(
            "codeType",
            "码类型",
            "码信息",
            [
                ("product", "产品码"),
                ("batch", "批次码"),
                ("forest-block", "林班码"),
                ("order", "订单码"),
            ],
            required=True,
        ),
        select_field(
            "productType",
            "产品品类",
            "产品溯源",
            [
                ("bamboo-timber", "竹材"),
                ("bamboo-shoot", "竹笋"),
                ("processed", "竹加工品"),
                ("understory", "林下产品"),
            ],
            required=True,
        ),
        text_field("batchNo", "产品批次", "产品溯源", required=True, maxLength=100),
        text_field("targetUrl", "扫码地址", "发布管理", required=True, input_type="url", maxLength=500),
        text_field("issuedAt", "签发时间", "发布管理", required=True, input_type="datetime-local"),
        select_field(
            "publishStatus",
            "启用状态",
            "发布管理",
            [
                ("draft", "草稿"),
                ("published", "已启用"),
                ("disabled", "已停用"),
            ],
            required=True,
        ),
        number_field("scanCount", "扫码次数", "使用统计", integer=True, unit="次", readOnly=True),
        relation_field("enterpriseIds", "责任企业", "enterprises", "issuer", required=True),
        relation_field("logisticsTraceIds", "物流溯源记录", "logistics-traces", "trace"),
    ],
    "supply-chain-finance": [
        select_field(
            "financeProduct",
            "金融产品",
            "融资申请",
            [
                ("order-finance", "订单融资"),
                ("inventory-pledge", "库存质押"),
                ("credit", "主体授信"),
            ],
            required=True,
        ),
        number_field("amount", "申请金额", "融资申请", required=True, unit="元"),
        number_field("termMonths", "融资期限", "融资申请", required=True, integer=True, unit="个月"),
        text_field("dueDate", "到期日期", "融资申请", required=True, input_type="date"),
        select_field(
            "reviewStatus",
            "审核状态",
            "审核风控",
            [
                ("draft", "草稿"),
                ("review", "审核中"),
                ("approved", "已通过"),
                ("rejected", "已驳回"),
                ("repaid", "已结清"),
            ],
            required=True,
        ),
        select_field(
            "riskLevel",
            "风险等级",
            "审核风控",
            [("low", "低"), ("medium", "中"), ("high", "高")],
            required=True,
        ),
        relation_field(
            "borrowerCooperativeIds",
            "融资合作社",
            "cooperatives",
            "borrower",
            multiple=False,
            relation_group="borrower",
            min_group_targets=1,
        ),
        relation_field(
            "borrowerEnterpriseIds",
            "融资企业",
            "enterprises",
            "borrower",
            multiple=False,
            relation_group="borrower",
            min_group_targets=1,
        ),
        relation_field("tradeMatchIds", "关联交易订单", "trade-matches", "collateral-order"),
    ],
    "price-indexes": [
        select_field(
            "productType",
            "产品品类",
            "指数对象",
            [
                ("bamboo-timber", "竹材"),
                ("bamboo-shoot", "竹笋"),
                ("processed", "竹加工品"),
            ],
            required=True,
        ),
        select_field(
            "qualityGrade",
            "质量等级",
            "指数对象",
            [("premium", "优等"), ("standard", "标准"), ("ordinary", "普通"), ("mixed", "综合")],
            required=True,
        ),
        *administrative_division_fields(section="采样区域", required=True, through="county"),
        number_field("price", "样本均价", "指数数据", required=True, unit="元/吨"),
        text_field("period", "采样周期", "指数数据", required=True, input_type="month"),
        number_field("sourceCount", "样本数量", "指数数据", required=True, integer=True, unit="个"),
        select_field(
            "publishStatus",
            "发布状态",
            "发布管理",
            [("draft", "草稿"), ("review", "待审核"), ("published", "已发布")],
            required=True,
        ),
    ],
    "mobile-service-channels": [
        select_field(
            "target",
            "服务对象",
            "渠道信息",
            [
                ("farmer", "竹农"),
                ("cooperative", "合作社"),
                ("enterprise", "竹企"),
                ("manager", "管理人员"),
            ],
            required=True,
        ),
        select_field(
            "channel",
            "服务渠道",
            "渠道信息",
            [("wechat", "微信端"), ("app", "移动 App"), ("h5", "H5"), ("mini-program", "小程序")],
            required=True,
        ),
        text_field("entry", "功能入口", "发布信息", required=True, input_type="url", maxLength=500),
        text_field("releaseVersion", "发布版本", "发布信息", required=True, maxLength=80),
        select_field(
            "publishStatus",
            "上线状态",
            "发布信息",
            [
                ("draft", "开发中"),
                ("review", "待上线"),
                ("published", "已上线"),
                ("offline", "已下线"),
            ],
            required=True,
        ),
        relation_field(
            "ownerCooperativeIds",
            "责任合作社",
            "cooperatives",
            "owner",
            multiple=False,
            relation_group="owner",
            min_group_targets=1,
        ),
        relation_field(
            "ownerEnterpriseIds",
            "责任企业",
            "enterprises",
            "owner",
            multiple=False,
            relation_group="owner",
            min_group_targets=1,
        ),
        relation_field("relatedPolicyIds", "关联政策", "policies", "policy"),
        relation_field("relatedServiceIds", "关联农资服务", "material-services", "service"),
    ],
}
